# Generated by Django 4.2.6 on 2023-10-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_auto_20160312_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_debit_record2wallet_credit_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet'),
        ),
    ]
